enum Events {
  CONSENT = 'CONSENT',
  SET_PARTICIPANT = 'SET_PARTICIPANT',
  SET_TASK = 'SET_TASK',
  START = 'START',
  END = 'START',
  ADD_INTERACTION = 'ADD_INTERACTION',
  SUBMIT_ANSWER = 'SUBMIT_ANSWER',
  SUBMIT_PREDICTION = 'SUBMIT_PREDICTION',
  ANNOTATE = 'ANNOTATE',
  TURN_INTO_SELECTION = 'TURN_INTO_SELECTION',
}

export default Events;
